backend:
  name: gitlab
  repo: dimitrisdervas/activecoala # Path to your GitLab repository
  auth_type: implicit # Required for implicit grant
  app_id: 8f6d3d560c8be1b473ae54e5823f8ad810b57456fd415058ab0bf7f414216777 # Application ID from your GitLab settings