---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/home2
  label: Home2
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/google6946197e72e58426
  label: Google6946197e72e58426
  create: all
  match: "**/*"
- type: directory
  path: content/search
  label: Search
  create: all
  match: "**/*"
- type: directory
  path: content/schoolowner
  label: Schoolowner
  create: all
  match: "**/*"
- type: directory
  path: content/subcategoriesCity
  label: Subcategoriescity
  create: all
  match: "**/*"
- type: directory
  path: content/search-lunr
  label: Search lunr
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
